/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as ComentariosRouteImport } from './routes/comentarios'
import { Route as IndexRouteImport } from './routes/index'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const ComentariosRoute = ComentariosRouteImport.update({
  id: '/comentarios',
  path: '/comentarios',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comentarios': typeof ComentariosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comentarios': typeof ComentariosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comentarios': typeof ComentariosRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/mapa': typeof MapaRoute
  '/perfil': typeof PerfilRoute
  '/sobre': typeof SobreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comentarios'
    | '/como-funciona'
    | '/mapa'
    | '/perfil'
    | '/sobre'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/comentarios' | '/como-funciona' | '/mapa' | '/perfil' | '/sobre'
  id:
    | '__root__'
    | '/'
    | '/comentarios'
    | '/como-funciona'
    | '/mapa'
    | '/perfil'
    | '/sobre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComentariosRoute: typeof ComentariosRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  MapaRoute: typeof MapaRoute
  PerfilRoute: typeof PerfilRoute
  SobreRoute: typeof SobreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comentarios': {
      id: '/comentarios'
      path: '/comentarios'
      fullPath: '/comentarios'
      preLoaderRoute: typeof ComentariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComentariosRoute: ComentariosRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  MapaRoute: MapaRoute,
  PerfilRoute: PerfilRoute,
  SobreRoute: SobreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
